apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: dev-team2
  namespace: apps2
spec:
  interval: 30s
  url: https://github.com/mombe090/flux2-multi-tenancy
  ref:
    branch: dev-team2
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: dev-team2
  namespace: apps2
spec:
  serviceAccountName: dev-team2
  interval: 30s
  sourceRef:
    kind: GitRepository
    name: dev-team2
  prune: true
  validation: client


