apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: dev-team
  namespace: apps
spec:
  interval: 30s
  url: https://github.com/mombe090/flux2-multi-tenancy
  branch: dev-team
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: dev-team
  namespace: apps
spec:
  serviceAccountName: dev-team
  interval: 30s
  sourceRef:
    kind: GitRepository
    name: dev-team
  prune: true
  validation: client


