---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tomcat
  namespace: apps
spec:
  serviceAccountName: dev-team
  chart:
    spec:
      chart: tomcat
      sourceRef:
        kind: HelmRepository
        name: bitnami
      version: '>=10.3.2'
  interval: 30s

